### PR TITLE
Added ability to install latest version

### PR DESCRIPTION
**Pull request by Thulium-Drake**
Hi Jeff!

I've processed your feedback on #3 and while I was at it, I also updated all other module names to their FQCN equivalents.

Met vriendelijke groet,
Jeff ;-)

### CODE REVIEW

**Comment by Thulium-Drake** [comment]
And ofcourse @tuxpeople, thanks for your work!

**Comment by geerlingguy** [comment]
I would rather leave it using the normal module names (and not the FQCN) at this time, as I'm still maintaining my roles without FQCNs (I'll make that transition across the board someday, but not yet).

**Comment by Thulium-Drake** [comment]
Fair enough, makes sense, it still works without FQCNs :)

**Comment by geerlingguy** [comment]
Hmm, looks like this would also require the addition of `jmespath` (e.g. `pip3 install jmespath`)?

**Comment by Thulium-Drake** [comment]
Ah yes, there's a lot of modules that require that, it actually surprises me that it isn't already a dependency to Ansible itself :)

Would adding a task to the molecule playbooks to install it be sufficient?

**Pull request closed without merging**
